name: Bug Report
description: Report unexpected behavior.
title: "Something is broken"
labels: ["type:bug"]
projects: [3nd3r1/6]
body:
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Run `kubin upload ./broken.json`
        2. Observe error: "Failed to parse JSON"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected vs. Actual Behavior"
      placeholder: |
        **Expected:** Upload succeeds with valid JSON.
        **Actual:** Crashes with unhandled exception.
  - type: dropdown
    id: component
    attributes:
      label: "Component"
      options:
        - "UI"
        - "API Gateway"
        - "Upload Orchestrator"
        - "Metadata Service"
        - "Storage Service"
        - "Log Processor"
        - "Query Service"
        - "Analytics Service"
        - "CLI"
  - type: textarea
    attributes:
      label: "Additional Context"
      placeholder: "(Optional) Add any other context here."
  - type: textarea
    attributes:
      label: "Possible Solution"
      placeholder: "(Optional) Suggest a fix if known."
