name: Chore
description: Internal improvements (tooling, refactors, etc.).
title: "Something is out of date"
labels: ["type:chore"]
projects: [3nd3r1/6]
body:
  - type: textarea
    attributes:
      label: "Description"
      placeholder: |
        What needs to be done?
        Example:
        Refactor the CLI command loader to support plugins.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: "Component"
      options:
        - "UI"
        - "API Gateway"
        - "Upload Orchestrator"
        - "Metadata Service"
        - "Storage Service"
        - "Log Processor"
        - "Query Service"
        - "Analytics Service"
        - "CLI"
