# Kubin - Main Configuration

# Global values shared across all subcharts
global:
  # Environment (development, staging, production)
  environment: production

  # Image configuration
  imageRegistry: ghcr.io/3nd3r1/kubin
  imageTag: "0.1.0"
  imagePullPolicy: IfNotPresent

  # Domain configuration
  domain: kubin.example.com

argocd:
  enabled: false

# =============================================================================
# KUBIN SERVICES
# =============================================================================

# API Gateway - Entry point for all requests
api-gateway:
  enabled: true

  # Image configuration (inherits from global if not specified)
  image:
    repository: kubin-api-gateway
    # tag: will use global.imageTag
    # pullPolicy: will use global.imagePullPolicy

  # Service configuration
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

  # Deployment configuration
  replicaCount: 1

  # Resource configuration

  # Environment variables
  env:
    SERVER_PORT: "8000"

  # Ingress configuration
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/rate-limit: "100"
    hosts:
      - host: api.kubin.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: kubin-api-tls
        hosts:
          - api.kubin.example.com

# =============================================================================
# INFRASTRUCTURE DEPENDENCIES
# =============================================================================

# PostgreSQL - Main database for metadata
postgresql:
  enabled: false

# Redis - Caching layer
redis:
  enabled: false

# =============================================================================
# FUTURE SERVICES (disabled for now)
# =============================================================================

# Upload Orchestrator - Handles snapshot uploads
upload-orchestrator:
  enabled: false

# Metadata Service - Manages snapshot metadata
metadata-service:
  enabled: false

# Storage Service - Manages S3/file operations
storage-service:
  enabled: false

# Log Processor - Processes and indexes logs
log-processor:
  enabled: false

# Query Service - Orchestrates data queries
query-service:
  enabled: false

# Analytics Service - ClickHouse analytics
analytics-service:
  enabled: false

# UI - React web interface
ui:
  enabled: false
